# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-08 16:25
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0009_auto_20170403_0127'),
    ]

    operations = [
        migrations.CreateModel(
            name='Planning',
            fields=[
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='teams.Team', verbose_name='équipe')),
                ('match1_time', models.TimeField(default=datetime.time(12, 30), validators=[django.core.validators.MinValueValidator(datetime.time(12, 30), message="L'heure de passage doit être après 12:30"), django.core.validators.MaxValueValidator(datetime.time(16, 30), message="L'heure de passage doit être avant 16:30")], verbose_name='match 1')),
                ('match2_time', models.TimeField(default=datetime.time(12, 30), validators=[django.core.validators.MinValueValidator(datetime.time(12, 30), message="L'heure de passage doit être après 12:30"), django.core.validators.MaxValueValidator(datetime.time(16, 30), message="L'heure de passage doit être avant 16:30")], verbose_name='match 2')),
                ('match3_time', models.TimeField(default=datetime.time(12, 30), validators=[django.core.validators.MinValueValidator(datetime.time(12, 30), message="L'heure de passage doit être après 12:30"), django.core.validators.MaxValueValidator(datetime.time(16, 30), message="L'heure de passage doit être avant 16:30")], verbose_name='match 3')),
                ('presentation_time', models.TimeField(default=datetime.time(12, 30), validators=[django.core.validators.MinValueValidator(datetime.time(12, 30), message="L'heure de passage doit être après 12:30"), django.core.validators.MaxValueValidator(datetime.time(16, 30), message="L'heure de passage doit être avant 16:30")], verbose_name='exposé')),
            ],
            options={
                'ordering': ['team'],
                'verbose_name': 'planning équipe',
            },
        ),
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_code', models.PositiveSmallIntegerField(choices=[(0, 'Scratch'), (1, 'Mindstorms'), (2, 'Arduino'), (3, 'RaspberryPi')], default=0, verbose_name='type classement')),
                ('general', models.PositiveSmallIntegerField(default=0, verbose_name='classement général')),
                ('robotics', models.PositiveSmallIntegerField(default=0, verbose_name='classement robotique')),
                ('research', models.PositiveSmallIntegerField(default=0, verbose_name='classement recherche')),
                ('poster', models.PositiveSmallIntegerField(default=0, verbose_name='classement poster')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.Team', verbose_name='équipe')),
            ],
            options={
                'ordering': ['type_code', 'team'],
                'verbose_name': 'classement',
            },
        ),
        migrations.CreateModel(
            name='PlanningControl',
            fields=[
            ],
            options={
                'verbose_name': 'Avancement',
                'proxy': True,
                'verbose_name_plural': 'Avancement',
            },
            bases=('event.planning',),
        ),
        migrations.AlterUniqueTogether(
            name='ranking',
            unique_together=set([('type_code', 'team')]),
        ),
    ]
