# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-11 21:40
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='planning',
            name='jury',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], default='1', max_length=1, verbose_name='jury'),
        ),
        migrations.AddField(
            model_name='planning',
            name='match1_table',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], default='A', max_length=1, verbose_name='table match 1'),
        ),
        migrations.AddField(
            model_name='planning',
            name='match2_table',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], default='A', max_length=1, verbose_name='table match 2'),
        ),
        migrations.AddField(
            model_name='planning',
            name='match3_table',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], default='A', max_length=1, verbose_name='table match 3'),
        ),
        migrations.AlterField(
            model_name='planning',
            name='match1_time',
            field=models.TimeField(default=datetime.time(12, 30), validators=[django.core.validators.MinValueValidator(datetime.time(12, 30), message="L'heure de passage doit être après 12:30"), django.core.validators.MaxValueValidator(datetime.time(16, 30), message="L'heure de passage doit être avant 16:30")], verbose_name='horaire match 1'),
        ),
        migrations.AlterField(
            model_name='planning',
            name='match2_time',
            field=models.TimeField(default=datetime.time(12, 30), validators=[django.core.validators.MinValueValidator(datetime.time(12, 30), message="L'heure de passage doit être après 12:30"), django.core.validators.MaxValueValidator(datetime.time(16, 30), message="L'heure de passage doit être avant 16:30")], verbose_name='horaire match 2'),
        ),
        migrations.AlterField(
            model_name='planning',
            name='match3_time',
            field=models.TimeField(default=datetime.time(12, 30), validators=[django.core.validators.MinValueValidator(datetime.time(12, 30), message="L'heure de passage doit être après 12:30"), django.core.validators.MaxValueValidator(datetime.time(16, 30), message="L'heure de passage doit être avant 16:30")], verbose_name='horaire match 3'),
        ),
    ]
