# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-11 22:07
from __future__ import unicode_literals

from django.db import migrations, models
import event.models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20170411_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planning',
            name='jury',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], default='1', max_length=1, validators=[event.models.validate_jury], verbose_name='jury'),
        ),
        migrations.AlterField(
            model_name='planning',
            name='match1_table',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], default='A', max_length=1, validators=[event.models.validate_table], verbose_name='table match 1'),
        ),
        migrations.AlterField(
            model_name='planning',
            name='match2_table',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], default='B', max_length=1, validators=[event.models.validate_table], verbose_name='table match 2'),
        ),
        migrations.AlterField(
            model_name='planning',
            name='match3_table',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], default='C', max_length=1, validators=[event.models.validate_table], verbose_name='table match 3'),
        ),
    ]
