# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-17 10:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_auto_20170412_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planning',
            name='team',
            field=models.OneToOneField(error_messages={'unique': 'Résultat déjà saisi pour cette équipe.'}, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='teams.Team', verbose_name='équipe'),
        ),
    ]
