# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-17 21:25
from __future__ import unicode_literals

from django.db import migrations, models
import event.models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_auto_20170417_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planning',
            name='match1_table',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], default='1', max_length=1, validators=[event.models.validate_table], verbose_name='table match 1'),
        ),
        migrations.AlterField(
            model_name='planning',
            name='match2_table',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], default='2', max_length=1, validators=[event.models.validate_table], verbose_name='table match 2'),
        ),
        migrations.AlterField(
            model_name='planning',
            name='match3_table',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], default='3', max_length=1, validators=[event.models.validate_table], verbose_name='table match 3'),
        ),
    ]
