# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-19 10:48
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_auto_20170417_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planning',
            name='match1_time',
            field=models.TimeField(default=datetime.time(12, 30), validators=[django.core.validators.MinValueValidator(datetime.time(12, 30), message="L'heure de passage doit être après 12:30"), django.core.validators.MaxValueValidator(datetime.time(17, 10), message="L'heure de passage doit être avant 17:10")], verbose_name='horaire match 1'),
        ),
        migrations.AlterField(
            model_name='planning',
            name='match2_time',
            field=models.TimeField(default=datetime.time(12, 30), validators=[django.core.validators.MinValueValidator(datetime.time(12, 30), message="L'heure de passage doit être après 12:30"), django.core.validators.MaxValueValidator(datetime.time(17, 10), message="L'heure de passage doit être avant 17:10")], verbose_name='horaire match 2'),
        ),
        migrations.AlterField(
            model_name='planning',
            name='match3_time',
            field=models.TimeField(default=datetime.time(12, 30), validators=[django.core.validators.MinValueValidator(datetime.time(12, 30), message="L'heure de passage doit être après 12:30"), django.core.validators.MaxValueValidator(datetime.time(17, 10), message="L'heure de passage doit être avant 17:10")], verbose_name='horaire match 3'),
        ),
        migrations.AlterField(
            model_name='planning',
            name='presentation_time',
            field=models.TimeField(default=datetime.time(12, 30), validators=[django.core.validators.MinValueValidator(datetime.time(12, 30), message="L'heure de passage doit être après 12:30"), django.core.validators.MaxValueValidator(datetime.time(17, 10), message="L'heure de passage doit être avant 17:10")], verbose_name='exposé'),
        ),
    ]
