# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-04 10:40
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DisplaySettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delay', models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='pause affichage')),
                ('checkin', models.BooleanField(default=False, verbose_name='pointage')),
                ('planning', models.BooleanField(default=False, verbose_name='planning')),
                ('scores', models.BooleanField(default=False, verbose_name='scores')),
                ('next_schedules', models.BooleanField(default=False, verbose_name='prochains passages')),
                ('message', models.CharField(blank=True, max_length=255, verbose_name='message')),
            ],
            options={
                'verbose_name': 'configuration',
                'verbose_name_plural': 'configuration',
            },
        ),
    ]
