# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-20 21:53
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('display', '0001_initial'), ('display', '0002_auto_20170403_0133'), ('display', '0003_auto_20170403_0139'), ('display', '0004_auto_20170403_2350'), ('display', '0005_auto_20170404_0014'), ('display', '0006_auto_20170404_0015'), ('display', '0007_displaysettings_next_schedules')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DisplaySettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'affichage',
            },
        ),
        migrations.AlterModelOptions(
            name='displaysettings',
            options={'verbose_name': 'configuration', 'verbose_name_plural': 'configuration'},
        ),
        migrations.AddField(
            model_name='displaysettings',
            name='delay',
            field=models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='pause affichage'),
        ),
        migrations.AddField(
            model_name='displaysettings',
            name='message',
            field=models.CharField(blank=True, max_length=255, verbose_name='message'),
        ),
        migrations.AddField(
            model_name='displaysettings',
            name='checkin',
            field=models.BooleanField(default=False, verbose_name='pointage'),
        ),
        migrations.AddField(
            model_name='displaysettings',
            name='planning',
            field=models.BooleanField(default=False, verbose_name='planning'),
        ),
        migrations.AddField(
            model_name='displaysettings',
            name='scores',
            field=models.BooleanField(default=False, verbose_name='scores'),
        ),
        migrations.AddField(
            model_name='displaysettings',
            name='next_schedules',
            field=models.BooleanField(default=False, verbose_name='prochains passages'),
        ),
    ]
