# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-02 23:33
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='displaysettings',
            options={'verbose_name': 'configuration', 'verbose_name_plural': 'configuration'},
        ),
        migrations.AddField(
            model_name='displaysettings',
            name='delay',
            field=models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='délai affichage'),
        ),
        migrations.AddField(
            model_name='displaysettings',
            name='message',
            field=models.TextField(blank=True, max_length=255, verbose_name='message'),
        ),
    ]
