# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-02 23:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0002_auto_20170403_0133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='displaysettings',
            name='message',
            field=models.CharField(blank=True, max_length=255, verbose_name='message'),
        ),
    ]
