# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-03 21:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0003_auto_20170403_0139'),
    ]

    operations = [
        migrations.AddField(
            model_name='displaysettings',
            name='checkin',
            field=models.BooleanField(default=False, verbose_name='présences'),
        ),
        migrations.AddField(
            model_name='displaysettings',
            name='planning',
            field=models.BooleanField(default=False, verbose_name='planning'),
        ),
        migrations.AddField(
            model_name='displaysettings',
            name='scores',
            field=models.BooleanField(default=False, verbose_name='scores'),
        ),
    ]
