# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-03 22:14
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0004_auto_20170403_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='displaysettings',
            name='delay',
            field=models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='pause affichage'),
        ),
    ]
