# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-03 22:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0005_auto_20170404_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='displaysettings',
            name='checkin',
            field=models.BooleanField(default=False, verbose_name='pointage'),
        ),
    ]
