# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-11 21:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0006_auto_20170404_0015'),
    ]

    operations = [
        migrations.AddField(
            model_name='displaysettings',
            name='next_schedules',
            field=models.BooleanField(default=False, verbose_name='prochains passages'),
        ),
    ]
