# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-26 21:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='status',
            field=models.CharField(choices=[('?', 'pas de réponse'), ('O', 'OK'), ('N', 'non disponible')], default='?', max_length=1, verbose_name='réponse'),
        ),
    ]
