# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-28 22:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0002_auto_20190326_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='notes',
            field=models.TextField(blank=True, verbose_name='notes'),
        ),
    ]
