# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-03-14 14:46
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import share.fields


class Migration(migrations.Migration):

    replaces = [('teams', '0001_initial'), ('teams', '0002_auto_20171104_1858'), ('teams', '0003_school_address'), ('teams', '0004_teamcontact'), ('teams', '0005_auto_20171105_0004'), ('teams', '0006_auto_20171105_0006'), ('teams', '0007_school_email'), ('teams', '0008_teamcontact_teacher_subject'), ('teams', '0009_auto_20171105_1609'), ('teams', '0010_auto_20171105_1753'), ('teams', '0011_auto_20171118_1311'), ('teams', '0012_teamcontact_school'), ('teams', '0013_auto_20190217_0014'), ('teams', '0014_auto_20200314_1545')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='nom')),
                ('city', models.CharField(max_length=50, verbose_name='ville')),
                ('zip_code', models.CharField(max_length=5, validators=[django.core.validators.RegexValidator('^[0-9]{5}$', message='Code postal invalide')], verbose_name='code postal')),
            ],
            options={
                'verbose_name': 'établissement scolaire',
                'verbose_name_plural': 'établissements scolaires',
                'ordering': ['zip_code', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('num', models.AutoField(primary_key=True, serialize=False, verbose_name='numéro')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='nom')),
                ('category_code', models.SmallIntegerField(choices=[(1, 'Mindstorms'), (2, 'Arduino'), (3, 'RaspberryPi')], default=1, verbose_name='catégorie')),
                ('present', models.BooleanField(default=False, verbose_name='présente')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='teams', to='teams.School', verbose_name='établissement scolaire')),
            ],
            options={
                'verbose_name': 'équipe',
                'ordering': ['num'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='prénom')),
                ('last_name', models.CharField(max_length=30, verbose_name='nom')),
                ('birth_date', models.DateField(verbose_name='date de naissance')),
                ('grade_code', models.SmallIntegerField(choices=[(1, 'PostBAC'), (2, 'Terminale'), (3, 'Première'), (4, 'Seconde'), (5, 'Troisième'), (6, 'Quatrième'), (7, 'Cinquième'), (8, 'Sixième'), (9, 'CM2'), (10, 'CM1')], default=8, verbose_name='niveau scolaire')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='members', to='teams.Team', verbose_name='équipe')),
            ],
            options={
                'verbose_name': 'équipier',
                'verbose_name_plural': 'équipiers',
            },
        ),
        migrations.AlterUniqueTogether(
            name='teammember',
            unique_together=set([('first_name', 'last_name')]),
        ),
        migrations.AddField(
            model_name='school',
            name='address',
            field=models.CharField(blank=True, max_length=250, verbose_name='adresse'),
        ),
        migrations.CreateModel(
            name='TeamContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('M', 'M.'), ('Mme', 'Mme'), ('Mlle', 'Mlle')], default='M', max_length=4, verbose_name='genre')),
                ('first_name', share.fields.FirstNameField(max_length=30, verbose_name='prénom')),
                ('last_name', share.fields.LastNameField(max_length=30, verbose_name='nom')),
                ('email', models.EmailField(blank=True, max_length=150, verbose_name='email')),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='téléphone')),
                ('taught_subject', models.CharField(blank=True, max_length=20, verbose_name='matière enseignée')),
            ],
            options={
                'verbose_name': 'contact',
                'verbose_name_plural': 'contacts',
                'ordering': ['last_name'],
            },
        ),
        migrations.AddField(
            model_name='team',
            name='contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='teams', to='teams.TeamContact', verbose_name='contact'),
        ),
        migrations.AddField(
            model_name='school',
            name='email',
            field=models.EmailField(blank=True, max_length=150, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='first_name',
            field=share.fields.FirstNameField(max_length=30, verbose_name='prénom'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='last_name',
            field=share.fields.LastNameField(max_length=30, verbose_name='nom'),
        ),
        migrations.AddField(
            model_name='teamcontact',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contacts', to='teams.School', verbose_name='établissement scolaire'),
        ),
        migrations.AlterField(
            model_name='school',
            name='city',
            field=share.fields.UpperCasedField(max_length=50, verbose_name='ville'),
        ),
        migrations.AlterField(
            model_name='teamcontact',
            name='gender',
            field=models.CharField(choices=[('M', 'M'), ('Mme', 'Mme'), ('Mlle', 'Mlle')], default='M', max_length=4, verbose_name='genre'),
        ),
    ]
