# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-20 21:51
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('teams', '0001_initial'), ('teams', '0002_auto_20170219_1952'), ('teams', '0003_auto_20170220_0013'), ('teams', '0004_team_category'), ('teams', '0005_auto_20170402_0014'), ('teams', '0006_auto_20170402_0022'), ('teams', '0007_auto_20170402_0122'), ('teams', '0008_auto_20170403_0038'), ('teams', '0009_auto_20170403_0127'), ('teams', '0010_auto_20170415_2312')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('num', models.AutoField(primary_key=True, serialize=False, verbose_name='numéro')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='nom')),
                ('grade', models.SmallIntegerField(choices=[(0, 'PostBAC'), (1, 'Terminale'), (2, 'Première'), (3, 'Seconde'), (4, 'Troisième'), (5, 'Quatrième'), (6, 'Cinquième'), (7, 'Sixième'), (8, 'CM2'), (9, 'CM1')], default=0, verbose_name='niveau scolaire')),
                ('arrived', models.BooleanField(default=False, verbose_name='arrivée')),
            ],
            options={
                'verbose_name': 'équipe',
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='nom')),
                ('city', models.CharField(max_length=50, verbose_name='ville')),
                ('zip_code', models.CharField(max_length=5, validators=[django.core.validators.RegexValidator('^[0-9]{5}$', message='Code postal invalide')], verbose_name='code postal')),
            ],
            options={
                'verbose_name': 'établissement scolaire',
            },
        ),
        migrations.AddField(
            model_name='team',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teams.School', verbose_name='établissement scolaire'),
        ),
        migrations.AlterModelOptions(
            name='school',
            options={'ordering': ['zip_code', 'name'], 'verbose_name': 'établissement scolaire', 'verbose_name_plural': 'établissements scolaires'},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['num'], 'verbose_name': 'équipe'},
        ),
        migrations.AddField(
            model_name='team',
            name='category_code',
            field=models.SmallIntegerField(choices=[(1, 'Mindstorms'), (2, 'Arduino'), (3, 'RaspberryPi')], default=1, verbose_name='catégorie'),
        ),
        migrations.RemoveField(
            model_name='team',
            name='grade',
        ),
        migrations.AddField(
            model_name='team',
            name='grade_code',
            field=models.SmallIntegerField(choices=[(1, 'PostBAC'), (2, 'Terminale'), (3, 'Première'), (4, 'Seconde'), (5, 'Troisième'), (6, 'Quatrième'), (7, 'Cinquième'), (8, 'Sixième'), (9, 'CM2'), (10, 'CM1')], default=8, verbose_name='niveau scolaire'),
        ),
        migrations.AlterField(
            model_name='school',
            name='name',
            field=models.CharField(max_length=50, verbose_name='nom'),
        ),
        migrations.AlterField(
            model_name='team',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='teams.School', verbose_name='établissement scolaire'),
        ),
        migrations.RemoveField(
            model_name='team',
            name='arrived',
        ),
        migrations.AddField(
            model_name='team',
            name='present',
            field=models.BooleanField(default=False, verbose_name='présente'),
        ),
        migrations.AlterField(
            model_name='team',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='teams', to='teams.School', verbose_name='établissement scolaire'),
        ),
    ]
