# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 18:41
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('num', models.AutoField(primary_key=True, serialize=False, verbose_name='numéro')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='nom')),
                ('grade', models.SmallIntegerField(choices=[(0, 'PostBAC'), (1, 'Terminale'), (2, 'Première'), (3, 'Seconde'), (4, 'Troisième'), (5, 'Quatrième'), (6, 'Cinquième'), (7, 'Sixième'), (8, 'CM2'), (9, 'CM1')], default=0, verbose_name='niveau scolaire')),
                ('school_name', models.CharField(blank=True, max_length=50, verbose_name='établissement')),
                ('city', models.CharField(max_length=50, verbose_name='ville')),
                ('zip_code', models.CharField(max_length=5, validators=[django.core.validators.RegexValidator('^[0-9]{5}$', message='Code postal invalide')], verbose_name='code postal')),
                ('arrived', models.BooleanField(default=False, verbose_name='arrivée')),
            ],
            options={
                'verbose_name': 'équipe',
            },
        ),
    ]
