# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-04 17:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='prénom')),
                ('last_name', models.CharField(max_length=30, verbose_name='nom')),
                ('birth_date', models.DateField(verbose_name='date de naissance')),
                ('grade_code', models.SmallIntegerField(choices=[(1, 'PostBAC'), (2, 'Terminale'), (3, 'Première'), (4, 'Seconde'), (5, 'Troisième'), (6, 'Quatrième'), (7, 'Cinquième'), (8, 'Sixième'), (9, 'CM2'), (10, 'CM1')], default=8, verbose_name='niveau scolaire')),
            ],
            options={
                'verbose_name': 'équipier',
                'verbose_name_plural': 'équipiers',
            },
        ),
        migrations.RemoveField(
            model_name='team',
            name='grade_code',
        ),
        migrations.AddField(
            model_name='teammember',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='members', to='teams.Team', verbose_name='équipe'),
        ),
        migrations.AlterUniqueTogether(
            name='teammember',
            unique_together=set([('first_name', 'last_name')]),
        ),
    ]
