# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 18:52
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='nom')),
                ('city', models.CharField(max_length=50, verbose_name='ville')),
                ('zip_code', models.CharField(max_length=5, validators=[django.core.validators.RegexValidator('^[0-9]{5}$', message='Code postal invalide')], verbose_name='code postal')),
            ],
            options={
                'verbose_name': 'établissement scolaire',
            },
        ),
        migrations.RemoveField(
            model_name='team',
            name='city',
        ),
        migrations.RemoveField(
            model_name='team',
            name='school_name',
        ),
        migrations.RemoveField(
            model_name='team',
            name='zip_code',
        ),
        migrations.AddField(
            model_name='team',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teams.School', verbose_name='établissement scolaire'),
        ),
    ]
