# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-04 22:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_auto_20171104_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='address',
            field=models.CharField(blank=True, max_length=250, verbose_name='adresse'),
        ),
    ]
