# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 23:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_auto_20170219_1952'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='school',
            options={'ordering': ['zip_code', 'name'], 'verbose_name': 'établissement scolaire', 'verbose_name_plural': 'établissements scolaires'},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['num'], 'verbose_name': 'équipe'},
        ),
    ]
