# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-04 23:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_school_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('M', 'M.'), ('Mme', 'Mme'), ('Mlle', 'Mlle')], default='M', max_length=4, verbose_name='genre')),
                ('first_name', models.CharField(max_length=30, verbose_name='prénom')),
                ('last_name', models.CharField(max_length=30, verbose_name='nom')),
                ('email', models.EmailField(blank=True, max_length=150, verbose_name='email')),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='téléphone')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contact', to='teams.Team', verbose_name='équipe')),
            ],
            options={
                'verbose_name': 'contact',
                'verbose_name_plural': 'contact',
                'ordering': ['last_name'],
            },
        ),
    ]
