# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-04 23:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_teamcontact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamcontact',
            name='team',
        ),
        migrations.AddField(
            model_name='team',
            name='contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='teams', to='teams.TeamContact', verbose_name='contact'),
        ),
    ]
