# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-01 22:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0005_auto_20170402_0014'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='category',
            new_name='category_code',
        ),
        migrations.AlterField(
            model_name='team',
            name='grade_code',
            field=models.SmallIntegerField(choices=[(1, 'PostBAC'), (2, 'Terminale'), (3, 'Première'), (4, 'Seconde'), (5, 'Troisième'), (6, 'Quatrième'), (7, 'Cinquième'), (8, 'Sixième'), (9, 'CM2'), (10, 'CM1')], default=8, verbose_name='niveau scolaire'),
        ),
    ]
