# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-02 22:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0007_auto_20170402_0122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='arrived',
        ),
        migrations.AddField(
            model_name='team',
            name='present',
            field=models.BooleanField(default=False, verbose_name='présente'),
        ),
    ]
