# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-05 13:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0007_school_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamcontact',
            name='teacher_subject',
            field=models.CharField(blank=True, max_length=20, verbose_name='matière enseignée'),
        ),
    ]
