# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-02 23:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0008_auto_20170403_0038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='category_code',
            field=models.SmallIntegerField(choices=[(1, 'Mindstorms'), (2, 'Arduino'), (3, 'RaspberryPi')], default=1, verbose_name='catégorie'),
        ),
    ]
