# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-05 15:09
from __future__ import unicode_literals

from django.db import migrations

import share.fields
import teams.models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0008_teamcontact_teacher_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='first_name',
            field=share.fields.FirstNameField(max_length=30, verbose_name='prénom'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='last_name',
            field=share.fields.LastNameField(max_length=30, verbose_name='nom'),
        ),
    ]
