# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-05 16:53
from __future__ import unicode_literals

from django.db import migrations
import teams.models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0009_auto_20171105_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamcontact',
            name='first_name',
            field=teams.models.FirstNameField(max_length=30, verbose_name='prénom'),
        ),
        migrations.AlterField(
            model_name='teamcontact',
            name='last_name',
            field=teams.models.LastNameField(max_length=30, verbose_name='nom'),
        ),
    ]
