# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-18 12:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0010_auto_20171105_1753'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teamcontact',
            old_name='teacher_subject',
            new_name='taught_subject',
        ),
    ]
