# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-18 12:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0011_auto_20171118_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamcontact',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contacts', to='teams.School', verbose_name='établissement scolaire'),
        ),
    ]
