# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-16 23:14
from __future__ import unicode_literals

from django.db import migrations
import teams.models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0012_teamcontact_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='city',
            field=teams.models.UpperCasedField(max_length=50, verbose_name='ville'),
        ),
    ]
