# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-03-14 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0013_auto_20190217_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamcontact',
            name='gender',
            field=models.CharField(choices=[('M', 'M'), ('Mme', 'Mme'), ('Mlle', 'Mlle')], default='M', max_length=4, verbose_name='genre'),
        ),
    ]
