# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 22:09
from __future__ import unicode_literals

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0003_auto_20170220_0013'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rob1Match',
            fields=[
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='teams.Team', verbose_name='équipe')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='heure de passage')),
                ('trips', models.PositiveSmallIntegerField(default=0, verbose_name='trajets')),
                ('variants', models.PositiveSmallIntegerField(default=0, verbose_name='variantes')),
                ('referee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='arbitre')),
            ],
            options={
                'verbose_name_plural': 'scores robotique 1',
                'verbose_name': 'score robotique 1',
            },
        ),
        migrations.CreateModel(
            name='Rob2Match',
            fields=[
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='teams.Team', verbose_name='équipe')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='heure de passage')),
                ('total_time', models.DurationField(default=datetime.timedelta(0, 150), validators=[django.core.validators.MaxValueValidator(datetime.timedelta(0, 150), message='nombre de trajets invalide')], verbose_name='temps total')),
                ('forward_trips', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(3, message='nombre de trajets invalide')], verbose_name='trajets aller')),
                ('return_trips', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(3, message='nombre de trajets invalide')], verbose_name='trajets retour')),
                ('deposited', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(3, message="nombre d'objets invalide")], verbose_name='objets déposés')),
                ('inside', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(3, message="nombre d'objets invalide")], verbose_name='objets dans la zone')),
                ('referee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='arbitre')),
            ],
            options={
                'verbose_name_plural': 'scores robotique 2',
                'verbose_name': 'score robotique 2',
            },
        ),
    ]
