# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-20 21:52
from __future__ import unicode_literals

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import match.models.generic


class Migration(migrations.Migration):

    replaces = [('match', '0001_initial'), ('match', '0002_auto_20170220_2310'), ('match', '0003_auto_20170220_2345'), ('match', '0004_robotics3'), ('match', '0005_auto_20170221_0118'), ('match', '0006_auto_20170222_0029'), ('match', '0007_auto_20170403_0038'), ('match', '0008_auto_20170417_1239'), ('match', '0009_auto_20170417_1249')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teams', '0003_auto_20170220_0013'),
    ]

    operations = [
        migrations.CreateModel(
            name='Robotics1',
            fields=[
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='teams.Team', verbose_name='équipe')),
                ('time', models.TimeField(auto_now_add=True, verbose_name='heure de passage')),
                ('trips', models.PositiveSmallIntegerField(default=0, verbose_name='trajets')),
                ('variants', models.PositiveSmallIntegerField(default=0, verbose_name='variantes')),
                ('referee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='arbitre')),
            ],
            options={
                'verbose_name': 'score robotique 1',
                'verbose_name_plural': 'scores robotique 1',
            },
        ),
        migrations.CreateModel(
            name='Robotics2',
            fields=[
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='teams.Team', verbose_name='équipe')),
                ('time', models.TimeField(auto_now_add=True, verbose_name='heure de passage')),
                ('total_time', models.DurationField(default=datetime.timedelta(0, 150), validators=[django.core.validators.MaxValueValidator(datetime.timedelta(0, 150), message='nombre de trajets invalide')], verbose_name='temps total')),
                ('forward_trips', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(3, message='nombre de trajets invalide')], verbose_name='trajets aller')),
                ('return_trips', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(3, message='nombre de trajets invalide')], verbose_name='trajets retour')),
                ('deposited', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(3, message="nombre d'objets invalide")], verbose_name='objets déposés')),
                ('inside', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(3, message="nombre d'objets invalide")], verbose_name='objets dans la zone')),
                ('referee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='arbitre')),
            ],
            options={
                'verbose_name': 'score robotique 2',
                'verbose_name_plural': 'scores robotique 2',
            },
        ),
        migrations.CreateModel(
            name='Robotics3',
            fields=[
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='teams.Team', verbose_name='équipe')),
                ('time', models.TimeField(auto_now_add=True, verbose_name='heure de passage')),
                ('trips', models.PositiveSmallIntegerField(default=0, verbose_name='trajets')),
                ('variants', models.PositiveSmallIntegerField(default=0, verbose_name='variantes')),
                ('moved_obstacles', models.PositiveSmallIntegerField(default=0, verbose_name='obstacles déplacés')),
                ('referee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='arbitre')),
            ],
            options={
                'verbose_name': 'score robotique 3',
                'verbose_name_plural': 'scores robotique 3',
            },
        ),
        migrations.AlterModelOptions(
            name='robotics1',
            options={'verbose_name': 'robotique 1', 'verbose_name_plural': 'robotique 1'},
        ),
        migrations.AlterModelOptions(
            name='robotics2',
            options={'verbose_name': 'robotique 2', 'verbose_name_plural': 'robotique 2'},
        ),
        migrations.AlterModelOptions(
            name='robotics3',
            options={'verbose_name': 'robotique 3', 'verbose_name_plural': 'robotique 3'},
        ),
        migrations.AlterField(
            model_name='robotics1',
            name='referee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='arbitre'),
        ),
        migrations.AlterField(
            model_name='robotics2',
            name='referee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='arbitre'),
        ),
        migrations.AlterField(
            model_name='robotics3',
            name='referee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='arbitre'),
        ),
        migrations.AlterModelOptions(
            name='robotics1',
            options={'verbose_name': 'résultat épreuve 1', 'verbose_name_plural': 'résultats épreuve 1'},
        ),
        migrations.AlterModelOptions(
            name='robotics2',
            options={'verbose_name': 'résultat épreuve 2', 'verbose_name_plural': 'résultats épreuve 2'},
        ),
        migrations.AlterModelOptions(
            name='robotics3',
            options={'verbose_name': 'résultat épreuve 3', 'verbose_name_plural': 'résultats épreuve 3'},
        ),
        migrations.AlterField(
            model_name='robotics2',
            name='deposited',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(3)], verbose_name='objets déposés'),
        ),
        migrations.AlterField(
            model_name='robotics2',
            name='forward_trips',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(3)], verbose_name='trajets aller'),
        ),
        migrations.AlterField(
            model_name='robotics2',
            name='inside',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(3)], verbose_name='objets dans la zone'),
        ),
        migrations.AlterField(
            model_name='robotics2',
            name='return_trips',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(3)], verbose_name='trajets retour'),
        ),
        migrations.RemoveField(
            model_name='robotics2',
            name='total_time',
        ),
        migrations.AddField(
            model_name='robotics2',
            name='used_time',
            field=match.models.generic.MatchDurationField(default=datetime.timedelta(0, 150), validators=[django.core.validators.MaxValueValidator(datetime.timedelta(0, 150))], verbose_name='temps utilisé'),
        ),
        migrations.AlterField(
            model_name='robotics1',
            name='team',
            field=models.OneToOneField(error_messages={'unique': 'Résultat déjà saisi pour cette équipe.'}, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='teams.Team', verbose_name='équipe'),
        ),
        migrations.AlterField(
            model_name='robotics2',
            name='team',
            field=models.OneToOneField(error_messages={'unique': 'Résultat déjà saisi pour cette équipe.'}, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='teams.Team', verbose_name='équipe'),
        ),
        migrations.AlterField(
            model_name='robotics3',
            name='team',
            field=models.OneToOneField(error_messages={'unique': 'Résultat déjà saisi pour cette équipe.'}, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='teams.Team', verbose_name='équipe'),
        ),
    ]
