# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-19 12:50
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations
import match.models.generic


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0002_auto_20190510_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='robotics1',
            name='used_time',
            field=match.models.generic.MatchDurationField(validators=[django.core.validators.MaxValueValidator(datetime.timedelta(0, 149))], verbose_name='temps utilisé'),
        ),
        migrations.AlterField(
            model_name='robotics2',
            name='used_time',
            field=match.models.generic.MatchDurationField(validators=[django.core.validators.MaxValueValidator(datetime.timedelta(0, 149))], verbose_name='temps utilisé'),
        ),
        migrations.AlterField(
            model_name='robotics3',
            name='used_time',
            field=match.models.generic.MatchDurationField(validators=[django.core.validators.MaxValueValidator(datetime.timedelta(0, 149))], verbose_name='temps utilisé'),
        ),
    ]
