# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 22:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0002_auto_20170220_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='robotics1',
            name='time',
            field=models.TimeField(auto_now_add=True, verbose_name='heure de passage'),
        ),
        migrations.AlterField(
            model_name='robotics2',
            name='time',
            field=models.TimeField(auto_now_add=True, verbose_name='heure de passage'),
        ),
    ]
