# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-05 16:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0002_auto_20171105_0000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='robotics1',
            name='trips',
        ),
        migrations.RemoveField(
            model_name='robotics1',
            name='variants',
        ),
        migrations.RemoveField(
            model_name='robotics2',
            name='deposited',
        ),
        migrations.RemoveField(
            model_name='robotics2',
            name='forward_trips',
        ),
        migrations.RemoveField(
            model_name='robotics2',
            name='inside',
        ),
        migrations.RemoveField(
            model_name='robotics2',
            name='return_trips',
        ),
        migrations.RemoveField(
            model_name='robotics2',
            name='used_time',
        ),
        migrations.RemoveField(
            model_name='robotics3',
            name='moved_obstacles',
        ),
        migrations.RemoveField(
            model_name='robotics3',
            name='trips',
        ),
        migrations.RemoveField(
            model_name='robotics3',
            name='variants',
        ),
        migrations.AddField(
            model_name='robotics1',
            name='quadrants',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='quadrants'),
        ),
        migrations.AddField(
            model_name='robotics2',
            name='moved_obstacles',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='obstacles déplacés'),
        ),
        migrations.AddField(
            model_name='robotics2',
            name='quadrants',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='quadrants'),
        ),
        migrations.AddField(
            model_name='robotics3',
            name='quadrants',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='quadrants'),
        ),
    ]
