# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-03-14 16:10
from __future__ import unicode_literals

from django.db import migrations
import match.models.generic


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0004_auto_20200314_1545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='robotics1',
            name='sections',
        ),
        migrations.RemoveField(
            model_name='robotics2',
            name='object_retrieved',
        ),
        migrations.RemoveField(
            model_name='robotics2',
            name='sections',
        ),
        migrations.RemoveField(
            model_name='robotics3',
            name='captured_objects',
        ),
        migrations.RemoveField(
            model_name='robotics3',
            name='deposited_objects',
        ),
        migrations.AddField(
            model_name='robotics1',
            name='travels',
            field=match.models.generic.ConstrainedCountField(default=0, max_value=6, min_value=0, verbose_name='trajets effectués'),
        ),
        migrations.AddField(
            model_name='robotics2',
            name='moved_obstacles',
            field=match.models.generic.ConstrainedCountField(default=0, max_value=3, min_value=0, verbose_name='obstacle déplacés'),
        ),
        migrations.AddField(
            model_name='robotics2',
            name='travels',
            field=match.models.generic.ConstrainedCountField(default=0, max_value=6, min_value=0, verbose_name='trajets effectués'),
        ),
        migrations.AddField(
            model_name='robotics3',
            name='bad_fruits',
            field=match.models.generic.ConstrainedCountField(default=0, max_value=3, min_value=0, verbose_name='fruits verts'),
        ),
        migrations.AddField(
            model_name='robotics3',
            name='good_fruits',
            field=match.models.generic.ConstrainedCountField(default=0, max_value=6, min_value=0, verbose_name='fruits mûrs'),
        ),
    ]
