# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 00:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0004_robotics3'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='robotics1',
            options={'verbose_name': 'robotique 1', 'verbose_name_plural': 'robotique 1'},
        ),
        migrations.AlterModelOptions(
            name='robotics2',
            options={'verbose_name': 'robotique 2', 'verbose_name_plural': 'robotique 2'},
        ),
        migrations.AlterModelOptions(
            name='robotics3',
            options={'verbose_name': 'robotique 3', 'verbose_name_plural': 'robotique 3'},
        ),
    ]
