# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 23:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0005_auto_20170221_0118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='robotics1',
            name='referee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='arbitre'),
        ),
        migrations.AlterField(
            model_name='robotics2',
            name='referee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='arbitre'),
        ),
        migrations.AlterField(
            model_name='robotics3',
            name='referee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='arbitre'),
        ),
    ]
