# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-02 22:38
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0006_auto_20170222_0029'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='robotics1',
            options={'verbose_name': 'résultat épreuve 1', 'verbose_name_plural': 'résultats épreuve 1'},
        ),
        migrations.AlterModelOptions(
            name='robotics2',
            options={'verbose_name': 'résultat épreuve 2', 'verbose_name_plural': 'résultats épreuve 2'},
        ),
        migrations.AlterModelOptions(
            name='robotics3',
            options={'verbose_name': 'résultat épreuve 3', 'verbose_name_plural': 'résultats épreuve 3'},
        ),
        migrations.AlterField(
            model_name='robotics2',
            name='deposited',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(3)], verbose_name='objets déposés'),
        ),
        migrations.AlterField(
            model_name='robotics2',
            name='forward_trips',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(3)], verbose_name='trajets aller'),
        ),
        migrations.AlterField(
            model_name='robotics2',
            name='inside',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(3)], verbose_name='objets dans la zone'),
        ),
        migrations.AlterField(
            model_name='robotics2',
            name='return_trips',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(3)], verbose_name='trajets retour'),
        ),
        migrations.AlterField(
            model_name='robotics2',
            name='total_time',
            field=models.DurationField(default=datetime.timedelta(0, 150), validators=[django.core.validators.MaxValueValidator(datetime.timedelta(0, 150))], verbose_name='temps total'),
        ),
    ]
