# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-17 10:49
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations
import match.models.generic


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0008_auto_20170417_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='robotics2',
            name='used_time',
            field=match.models.generic.MatchDurationField(default=datetime.timedelta(0, 150), validators=[django.core.validators.MaxValueValidator(datetime.timedelta(0, 150))], verbose_name='temps utilisé'),
        ),
    ]
