# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-01 23:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0007_auto_20170402_0122'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchWork',
            fields=[
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='teams.Team', verbose_name='équipe')),
                ('jury', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3)], default=1, verbose_name='jury')),
                ('time', models.TimeField(auto_now_add=True, verbose_name='heure de passage')),
                ('topic_selection', models.PositiveSmallIntegerField(choices=[(0, 'nul'), (1, 'médiocre'), (2, 'passable'), (3, 'satisfaisant'), (4, 'excellent')], default=0, verbose_name='pertinence du sujet')),
                ('documentation', models.PositiveSmallIntegerField(choices=[(0, 'nul'), (1, 'médiocre'), (2, 'passable'), (3, 'satisfaisant'), (4, 'excellent')], default=0, verbose_name='travail de documentation')),
                ('presentation', models.PositiveSmallIntegerField(choices=[(0, 'nul'), (1, 'médiocre'), (2, 'passable'), (3, 'satisfaisant'), (4, 'excellent')], default=0, verbose_name='qualité de la présentation')),
                ('expression', models.PositiveSmallIntegerField(choices=[(0, 'nul'), (1, 'médiocre'), (2, 'passable'), (3, 'satisfaisant'), (4, 'excellent')], default=0, verbose_name='expression orale')),
                ('answers', models.PositiveSmallIntegerField(choices=[(0, 'nul'), (1, 'médiocre'), (2, 'passable'), (3, 'satisfaisant'), (4, 'excellent')], default=0, verbose_name='réponses aux questions')),
            ],
            options={
                'ordering': ['team'],
                'verbose_name': 'exposé',
            },
        ),
    ]
