# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-04 23:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentarywork',
            name='team',
            field=models.OneToOneField(error_messages={'unique': 'Données déjà saisies pour cette équipe.'}, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='teams.Team', verbose_name='équipe'),
        ),
        migrations.AlterField(
            model_name='poster',
            name='team',
            field=models.OneToOneField(error_messages={'unique': 'Données déjà saisies pour cette équipe.'}, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='teams.Team', verbose_name='équipe'),
        ),
    ]
