# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-02 00:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0007_auto_20170402_0122'),
        ('research', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poster',
            fields=[
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='teams.Team', verbose_name='équipe')),
                ('conformity', models.PositiveSmallIntegerField(choices=[(0, 'nul'), (1, 'médiocre'), (2, 'passable'), (3, 'satisfaisant'), (4, 'excellent')], default=0, verbose_name='conformité')),
                ('quality', models.PositiveSmallIntegerField(choices=[(0, 'nul'), (1, 'médiocre'), (2, 'passable'), (3, 'satisfaisant'), (4, 'excellent')], default=0, verbose_name='réalisation')),
                ('originality', models.PositiveSmallIntegerField(choices=[(0, 'nul'), (1, 'médiocre'), (2, 'passable'), (3, 'satisfaisant'), (4, 'excellent')], default=0, verbose_name='originalité')),
            ],
            options={
                'verbose_name': 'poster',
                'ordering': ['team'],
            },
        ),
    ]
