# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-02 12:19
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0007_auto_20170402_0122'),
        ('research', '0002_poster'),
    ]

    operations = [
        migrations.CreateModel(
            name='Planning',
            fields=[
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='teams.Team', verbose_name='équipe')),
                ('robotics1_time', models.TimeField(validators=[django.core.validators.MinValueValidator(datetime.time(12, 30), message="L'heure de passage doit être après 12:30"), django.core.validators.MaxValueValidator(datetime.time(17, 30), message="L'heure de passage doit être avant 17:30")], verbose_name='heure de passage match 1')),
                ('robotics2_time', models.TimeField(validators=[django.core.validators.MinValueValidator(datetime.time(12, 30), message="L'heure de passage doit être après 12:30"), django.core.validators.MaxValueValidator(datetime.time(17, 30), message="L'heure de passage doit être avant 17:30")], verbose_name='heure de passage match 2')),
                ('robotics3_time', models.TimeField(validators=[django.core.validators.MinValueValidator(datetime.time(12, 30), message="L'heure de passage doit être après 12:30"), django.core.validators.MaxValueValidator(datetime.time(17, 30), message="L'heure de passage doit être avant 17:30")], verbose_name='heure de passage match 3')),
                ('presentation_time', models.TimeField(validators=[django.core.validators.MinValueValidator(datetime.time(12, 30), message="L'heure de passage doit être après 12:30"), django.core.validators.MaxValueValidator(datetime.time(17, 30), message="L'heure de passage doit être avant 17:30")], verbose_name='heure de passage exposé')),
            ],
            options={
                'ordering': ['team'],
                'verbose_name': 'poster',
            },
        ),
    ]
