# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-02 12:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0003_planning'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planning',
            name='team',
        ),
        migrations.DeleteModel(
            name='Planning',
        ),
    ]
