# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-02 14:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0006_auto_20170402_1617'),
    ]

    operations = [
        migrations.RenameField(
            model_name='presentation',
            old_name='quality',
            new_name='presentation',
        ),
    ]
