# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-02 14:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0007_auto_20170402_1618'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Presentation',
            new_name='DocumentaryWork',
        ),
    ]
