# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-11 21:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0009_auto_20170403_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentarywork',
            name='answers',
            field=models.PositiveSmallIntegerField(choices=[(0, '0 - insuffisant'), (1, '1 - médiocre'), (2, '2 - moyen'), (3, '3 - bien'), (4, '4 - très bien')], default=0, verbose_name='réponses aux questions'),
        ),
        migrations.AlterField(
            model_name='documentarywork',
            name='documentation',
            field=models.PositiveSmallIntegerField(choices=[(0, '0 - insuffisant'), (1, '1 - médiocre'), (2, '2 - moyen'), (3, '3 - bien'), (4, '4 - très bien')], default=0, verbose_name='travail de documentation'),
        ),
        migrations.AlterField(
            model_name='documentarywork',
            name='expression',
            field=models.PositiveSmallIntegerField(choices=[(0, '0 - insuffisant'), (1, '1 - médiocre'), (2, '2 - moyen'), (3, '3 - bien'), (4, '4 - très bien')], default=0, verbose_name='expression orale'),
        ),
        migrations.AlterField(
            model_name='documentarywork',
            name='presentation',
            field=models.PositiveSmallIntegerField(choices=[(0, '0 - insuffisant'), (1, '1 - médiocre'), (2, '2 - moyen'), (3, '3 - bien'), (4, '4 - très bien')], default=0, verbose_name='qualité de la présentation'),
        ),
        migrations.AlterField(
            model_name='documentarywork',
            name='topic_selection',
            field=models.PositiveSmallIntegerField(choices=[(0, '0 - insuffisant'), (1, '1 - médiocre'), (2, '2 - moyen'), (3, '3 - bien'), (4, '4 - très bien')], default=0, verbose_name='pertinence du sujet'),
        ),
        migrations.AlterField(
            model_name='poster',
            name='conformity',
            field=models.PositiveSmallIntegerField(choices=[(0, '0 - insuffisant'), (1, '1 - médiocre'), (2, '2 - moyen'), (3, '3 - bien'), (4, '4 - très bien')], default=0, verbose_name='conformité'),
        ),
        migrations.AlterField(
            model_name='poster',
            name='originality',
            field=models.PositiveSmallIntegerField(choices=[(0, '0 - insuffisant'), (1, '1 - médiocre'), (2, '2 - moyen'), (3, '3 - bien'), (4, '4 - très bien')], default=0, verbose_name='originalité'),
        ),
        migrations.AlterField(
            model_name='poster',
            name='quality',
            field=models.PositiveSmallIntegerField(choices=[(0, '0 - insuffisant'), (1, '1 - médiocre'), (2, '2 - moyen'), (3, '3 - bien'), (4, '4 - très bien')], default=0, verbose_name='réalisation'),
        ),
    ]
