# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-19 10:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0011_auto_20170417_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentarywork',
            name='done',
            field=models.BooleanField(default=False, verbose_name='soutenu'),
        ),
    ]
