# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-19 10:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0012_documentarywork_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentarywork',
            name='evaluation_available',
            field=models.BooleanField(default=False, verbose_name='évaluation disponible'),
        ),
        migrations.AlterField(
            model_name='documentarywork',
            name='done',
            field=models.BooleanField(default=False, verbose_name='fait'),
        ),
    ]
